source/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::group(['middleware' => 'auth'], function(){
    # TENANT
    Route::group(['prefix' => 'tenant', 'namespace' => 'Tenant'] ,function(){
        Route::get('/', 'TenantController@index')->name('tenant.index');
        Route::post('/', 'TenantController@storeTenant')->name('tenant.store');
        Route::get('/{id}', 'TenantController@showTenant')->name('tenant.show');
        Route::post('/setActive', 'TenantController@setActive')->name('tenant.setActive');
        Route::get('/create','TenantController@createTenant')->name('tenant.create');
        Route::get('/list', 'TenantController@listTenant')->name('tenant.list');
    });

    # TENANT'S RESOURCES
    Route::group(['prefix'=> 'tenant/{tenant_id}', 'namespace' => 'Tenant'], function(){
        Route::resource('/product', 'ProductController');
        Route::resource('/category', 'CategoryController');
        Route::resource('/unit','UnitController');
        Route::resource('/order', 'OrderController');
    });

    # ADMINISTRATOR
    Route::group(['middleware' => 'superadmin'], function(){
        Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function(){
            Route::get('/', 'HomeController@index')->name('admin.home');
            Route::group(['prefix' =>'component'], function(){
                Route::get('/index', 'ComponentController@index')->name('component.index');
                Route::get('/create', 'ComponentController@create')->name('component.create');
                Route::post('/create', 'ComponentController@store')->name('component.store');
            });
        });
    });
    # NORMAL USER
});

# GUEST
Route::group(['prefix' => 'shop', 'namespace' =>'Tenant'], function(){
    Route::get('/{slug}' , 'PageController@index')->name('page.index');
    Route::get('/{slug}/product', 'PageController@shop')->name('page.shop');
    Route::get('/{slug}/product/{product_slug}', 'PageController@shopSingle')->name('page.shopSingle');
    Route::post('/{slug}/product{product_slug}', 'PageController@addToCart')->name('page.addToCart');
    Route::get('/{slug}/category/{id}', 'PageController@category')->name('page.category');
});

source/app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    public function products(){
        return $this->hasMany('App\Product');
    }
}

source/app/Http/Controllers/Tenant/UnitController.php
<?php

namespace App\Http\Controllers\Tenant;

use App\Http\Controllers\Controller;
use App\Unit;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class UnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $tenant = Auth::user()->tenants()->where('id' , $request->tenant_id)->first();
        $units = $tenant->units()->get();
        return view('/tenant/backend/unit/index')->with('units', $units)->with('tenant', $tenant);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('/tenant/backend/unit/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $unit = new Unit();
        $unit->name = $request->name;
        $tenant = Auth::user()->tenants()->where('id', $request->tenant_id)->first();
        $tenant->units()->save($unit);
        return redirect()->route('unit.index', ['tenant_id' => $tenant->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

source/resources/views/tenant/backend/unit/index.blade.php
@extends('/tenant/backend/base')
@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <button type="button"
                                class="col-md-12 btn btn-success"
                                data-toggle="modal"
                                data-target="#createUnit">Create New Unit</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Units Table</strong>
                    </div>
                    <div class="card-body">
                        <div class="table-stats order-table ov-h">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th class="col">#</th>
                                    <th class="col">Name</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($units as $index => $unit)
                                    <tr>
                                        <td class="col">{{$index + 1 }}</td>

                                        <td><span class="col">{{$unit->name}}</span> </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div> <!-- /.table-stats -->
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="createUnit" tabindex="-1" role="dialog" aria-labelledby="mediumModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="mediumModalLabel">Create Unit</h5>
                </div>
                <div class="modal-body">
                    <form id="createUnitForm" method="POST" action="{{route('unit.store', ['tenant_id' =>  $tenant->id])}}">
                        @csrf
                        <div class="form-group">
                            <label for="name" class="form-control-label">Name</label>
                            <input type="text" name="name" id="name" placeholder="Enter your unit name" class="form-control">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary" form="createUnitForm">Confirm</button>
                </div>
            </div>
        </div>
    </div>

@endsection