source/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::group(['middleware' => 'auth'], function(){
    # TENANT
    Route::group(['prefix' => 'tenant', 'namespace' => 'Tenant'] ,function(){
        Route::get('/', 'TenantController@index')->name('tenant.index');
        Route::post('/', 'TenantController@storeTenant')->name('tenant.store');
        Route::get('/{id}', 'TenantController@showTenant')->name('tenant.show');
        Route::post('/setActive', 'TenantController@setActive')->name('tenant.setActive');
        Route::get('/create','TenantController@createTenant')->name('tenant.create');
        Route::get('/list', 'TenantController@listTenant')->name('tenant.list');
    });

    # TENANT'S RESOURCES
    Route::group(['prefix'=> 'tenant/{tenant_id}', 'namespace' => 'Tenant'], function(){
        Route::resource('/product', 'ProductController');
        Route::resource('/category', 'CategoryController');
        Route::resource('/unit','UnitController');
        Route::resource('/order', 'OrderController');
    });

    # ADMINISTRATOR
    Route::group(['middleware' => 'superadmin'], function(){
        Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function(){
            Route::get('/', 'HomeController@index')->name('admin.home');
            Route::group(['prefix' =>'component'], function(){
                Route::get('/index', 'ComponentController@index')->name('component.index');
                Route::get('/create', 'ComponentController@create')->name('component.create');
                Route::post('/create', 'ComponentController@store')->name('component.store');
            });
        });
    });
    # NORMAL USER
});

# GUEST
Route::group(['prefix' => 'shop', 'namespace' =>'Tenant'], function(){
    Route::get('/{slug}' , 'PageController@index')->name('page.index');
    Route::get('/{slug}/product', 'PageController@shop')->name('page.shop');
    Route::get('/{slug}/product/{product_slug}', 'PageController@shopSingle')->name('page.shopSingle');
    Route::post('/{slug}/product{product_slug}', 'PageController@addToCart')->name('page.addToCart');
    Route::get('/{slug}/category/{id}', 'PageController@category')->name('page.category');
});

source/app/Tenant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Tenant extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'name','address','phone','email', 'user_id', 'slug', 'description'
    ];


    /**
     * @return BelongsTo
     */
    public function user(){
        return $this->belongsTo('App\User');
    }

    /**
     * @return HasMany
     */
    public function products(){
        return $this->hasMany('App\Product');
    }

    /**
     * @return HasMany
     */
    public function cms(){
        return $this->hasMany('App\Cms');
    }

    /**
     * @return HasMany
     */
    public function categories(){
        return $this->hasMany('App\Category');
    }

    /**
     * @return BelongsToMany
     */
    public function currencies(){
        return $this->belongsToMany('App\Currency','tenant_currencies', 'tenant_id', 'currency_id');
    }

    /**
     * @return HasMany
     */
    public function units(){
        return $this->hasMany('App\Unit');
    }

    /**
     * @return BelongsToMany
     */
    public function components(){
        return $this->belongsToMany('App\Component','tenant_components', 'tenant_id','component_id');
    }

    public function orders(){
        return $this->hasMany('App\Order');
    }
}

source/app/Http/Controllers/Tenant/CategoryController.php
<?php

namespace App\Http\Controllers\Tenant;

use App\Category;
use App\Repositories\Eloquents\CategoryRepository;
use App\Repositories\Eloquents\TenantRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{
    protected $tenantRepository;
    protected $categoryRepository;

    /**
     * CategoryController constructor.
     * @param CategoryRepository $categoryRepository
     */
    public function __construct(CategoryRepository $categoryRepository, TenantRepository $tenantRepository)
    {
        $this->tenantRepository = $tenantRepository;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $tenant = $this->tenantRepository->find($request->tenant_id);
        $categories = $tenant->categories()->get();
        $title = 'Category';
        return view('/tenant/backend/category/index')->with('categories', $categories)->with('title', $title)->with('tenant', $tenant);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {

        if ($request->method() === 'POST'){
            $data = array(
                'name' => $request->name,
                'tenant_id' => $request->tenant_id,
                'description' => $request->description,
                'parents_id' => ($request->parent) ? $request->parent : null,
                'image' => $request->file('image')
            );
            if ($this->categoryRepository->create($data)){
                return redirect()->route('category.index', ['tenant_id' => $request->tenant_id]);
            }
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function update(Request $request)
    {
        $data = array(
            'name' => $request->name,
            'tenant_id' => $request->tenant_id,
            'description' => $request->description,
            'image' => $request->file('image')
        );
        if ($this->categoryRepository->update($request->category, $data)){
            return redirect()->route('category.index', ['tenant_id' => $request->tenant_id]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @return Response
     */
    public function destroy(Request $request)
    {
        if ($this->categoryRepository->delete($request->category)){
            return redirect()->route('category.index', ['tenant_id' => $request->tenant_id]);
        }
    }
}

source/app/Http/Controllers/Tenant/ComponentController.php
<?php

namespace App\Http\Controllers\Tenant;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ComponentController extends Controller
{
    //
}

source/app/Http/Controllers/Tenant/OrderController.php
<?php

namespace App\Http\Controllers\Tenant;

use App\Http\Controllers\Controller;
use App\Repositories\Eloquents\OrderRepository;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class OrderController extends Controller
{
    protected $orderRepository;

    /**
     * OrderController constructor.
     * @param OrderRepository $orderRepository
     */
    public function __construct(OrderRepository $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

source/app/Http/Controllers/Tenant/PageController.php
<?php

namespace App\Http\Controllers\Tenant;

use App\Category;
use App\Http\Controllers\Controller;
use App\Repositories\Eloquents\CategoryRepository;
use App\Repositories\Eloquents\ProductRepository;
use App\Repositories\Eloquents\TenantRepository;
use App\Tenant;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\View\View;

class PageController extends Controller
{
    /**
     * @var TenantRepository
     */
    protected $tenantRepository;
    /**
     * @var CategoryRepository
     */
    protected $categoryRepository;
    /**
     * @var ProductRepository
     */
    protected $productRepository;

    /**
     * PageController constructor.
     * @param TenantRepository $tenantRepository
     * @param CategoryRepository $categoryRepository
     * @param ProductRepository $productRepository
     */
    public function __construct(TenantRepository $tenantRepository, CategoryRepository $categoryRepository, ProductRepository $productRepository)
    {
        $this->tenantRepository = $tenantRepository;
        $this->categoryRepository = $categoryRepository;
        $this->productRepository = $productRepository;
    }

    /**
     * @param Request $request
     * @return Factory|View
     */
    public function index(Request $request){
        $tenant = $this->tenantRepository->get($request->slug, null);
        $slug = $request->slug;
        $data = array(
            # Collections
            'collections' => $this->categoryRepository->getCategoryNoParent($tenant->id),
            # Popular items
            'popular_items' => $this->productRepository->popular($tenant, null, 6),
        );
        return view('/tenant/frontend/index/index')->with('tenant', $tenant)->with('data', $data)->with('slug', $slug);
    }

    /**
     * @param Request $request
     * @return Factory|View
     */
    public function shop(Request $request){
        $tenant = Tenant::where('slug', $request->slug)->first();
        $product = $tenant->products()->where('slug', $request->productSlug)->first();
        return view('/tenant/frontend/product/shop')->with('tenant', $tenant)->with('product', $product);
    }

    /**
     * @param Request $request
     * @return Factory|View
     */
    public function shopSingle(Request $request){
        $tenant = Tenant::where('slug', $request->slug)->first();
        $slug = $request->slug;
        $product = $this->productRepository->findBySlug($request->product_slug, $tenant);
        $data = array(
            'collections' => $this->categoryRepository->getCategoryNoParent($tenant->id),
            'product' => $product
        );
        return view('/tenant/frontend/product/detail')->with('tenant', $tenant)->with('data', $data)->with('slug', $slug);
    }

    /**
     * @param Request $request
     * @return Factory|View
     */
    public function category(Request $request){
        $tenant = Tenant::where('slug', $request->slug)->first();
        $category = Category::where('id', $request->id)->first();
        $products= $category->products()->get();
        return view('/tenant/frontend/product/shop')
            ->with('tenant', $tenant)
            ->with('products', $products)
            ->with('tenant', $tenant);
    }

    public function addToCart(Request $request){
        $tenant = Tenant::where('slug', $request->slug)->first();
        $product = $this->productRepository->findBySlug($request->slug, $tenant);
        # TODO: Add to cart
        # TODO: Flash message
    }
}

source/app/Http/Controllers/Tenant/ProductController.php
<?php

namespace App\Http\Controllers\Tenant;

use App\Currency;
use App\Image;
use App\Product;
use App\Repositories\Eloquents\ProductRepository;
use App\Repositories\Eloquents\TenantRepository;
use App\Unit;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class ProductController extends Controller
{

    protected $productRepository;
    protected $tenantRepository;

    /**
     * ProductController constructor.
     * @param ProductRepository $productRepository
     * @param TenantRepository $tenantRepository
     */
    public function __construct(ProductRepository $productRepository, TenantRepository $tenantRepository)
    {
        $this->productRepository = $productRepository;
        $this->tenantRepository = $tenantRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $units = Unit::get();
        $tenant = Auth::user()->tenants()->where('id', $request->tenant_id)->first();
        $products = $this->productRepository->all($tenant);
        $categories = $tenant->categories()->get();
        return view('/tenant/backend/product/index')
            ->with('products', $products)
            ->with('tenant', $tenant)
            ->with('units', $units)
            ->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     */
    public function store(Request $request)
    {
        $tenant = Auth::user()->tenants()->where('id', $request->tenant_id)->first();
        $product = new Product(array(
            'name' => $request->name,
            'slug' => $request->slug,
            'overview' => $request->overview,
            'description' => $request->description,
            'quantity' => $request->quantity,
            'currency_id' => 1,
            'price' => $request->price,
            'tenant_id' => $tenant->id,
            'views' => 0,
            'unit_id' =>$request->unit
        ));
        $product->save();
        if ($request->file('images')){
            foreach($request->file('images') as $file){
                $image = new Image();
                $product->images()->save($image);
                $image->path = $file->storeAs('public/tenant/'.''.$tenant->id.''.'/product/'.''.$product->slug,'image-'.''.$image->id);
                $image->path = str_replace('public/','',$image->path);
                $product->images()->save($image);
            }
        }
        redirect()->route('product.index', ['tenant->id' => $tenant->id]);
    }

}

source/app/Http/Controllers/Tenant/TenantController.php
<?php

namespace App\Http\Controllers\Tenant;

use App\Repositories\EloquentRepository;
use App\Repositories\Eloquents\TenantRepository;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class TenantController extends Controller
{
    /**
     * @var TenantRepositoryInterface|EloquentRepository
     */
    protected $tenantRepository;

    /**
     * TenantController constructor.
     * @param TenantRepository $tenantRepository
     */
    public function __construct(TenantRepository $tenantRepository)
    {
        $this->middleware('auth');
        $this->tenantRepository = $tenantRepository;
    }

    /**
     * @return Factory|View
     */
    public function index(){
        $tenants = $this->tenantRepository->get(null, Auth::user());
        return view('/tenant/backend/user/index')->with('tenants', $tenants);
    }

    public function showTenant(Request $request){
        $tenant = $this->tenantRepository->find($request->id);
        return view('/tenant/backend/show')->with('tenant', $tenant);
    }

    /**
     * @param Request $request
     * @return Factory|RedirectResponse|View
     */
    public function storeTenant(Request $request){
        if ($request->method() === 'POST'){
            $data = array(
                'name' => $request->name,
                'email' => $request->email,
                'address' => $request->address,
                'phone' => $request->phone,
                'user_id' => Auth::user()->id,
                'slug' => $request->slug,
                'description' => $request->description,
                'logo' => $request->file('logo')
            );
            if ($this->tenantRepository->create($data)){
                return redirect(route('tenant.index'));
            } else {
                // RESPONSE ERRORS
            }
        } else {
            return $this->index();
        }
    }
}

source/resources/views/tenant/backend/base.blade.php
@include('/tenant/backend/baseHeader')
@include('/tenant/backend/baseSidebar')
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>TripleH Admin</title>
    <meta name="description" content="Ela Admin - Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{{asset('assets/template/css/cs-skin-elastic.css')}}">
    <link rel="stylesheet" href="{{asset('assets/template/css/style.css')}}">
    @yield('stylesheets')
    <title>@yield('title')</title>
</head>

<body>
@yield('sidebar')

<div id="right-panel" class="right-panel">

    @yield('header')
    @yield('content')
    <div class="clearfix"></div>

</div>
<script src="{{asset('/jquery.min.js')}}" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
<script src="{{asset('/bootstrap.js')}}" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
@yield('scripts')

</body>
</html>

source/resources/views/tenant/backend/baseBreakcumb.blade.php
@section('breakcumb')
    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-12">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <h1></h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

source/resources/views/tenant/backend/baseHeader.blade.php
@section('header')
    <header id="header" class="header">
        <div class="top-left">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{route('tenant.index')}}"><img src="{{asset('assets/template/images/logo.png')}}" alt="TripleH"></a>
                <a class="navbar-brand hidden" href="{{route('tenant.index')}}"><img src="{{asset('assets/template/images/logo2.png')}}" alt="TripleH"></a>
                <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
            </div>
        </div>

    <div class="top-right">
        <div class="header-menu">
            <div class="header-left">
                <button class="search-trigger"><i class="fa fa-search"></i></button>
                <div class="form-inline">
                    <form class="search-form">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                        <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                    </form>
                </div>

                <div class="dropdown for-notification">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="count bg-danger">3</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="notification">
                        <p class="red">You have 3 Notification</p>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-check"></i>
                            <p>Server #1 overloaded.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-info"></i>
                            <p>Server #2 overloaded.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-warning"></i>
                            <p>Server #3 overloaded.</p>
                        </a>
                    </div>
                </div>

                <div class="dropdown for-message">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-envelope"></i>
                        <span class="count bg-primary">4</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="message">
                        <p class="red">You have 4 Mails</p>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{{asset('assets/template/images/avatar/1.jpg')}}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Jonathan Smith</span>
                                <span class="time float-right">Just now</span>
                                <p>Hello, this is an example msg</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{{asset('assets/template/images/avatar/2.jpg')}}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Jack Sanders</span>
                                <span class="time float-right">5 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{{asset('assets/template/images/avatar/3.jpg')}}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Cheryl Wheeler</span>
                                <span class="time float-right">10 minutes ago</span>
                                <p>Hello, this is an example msg</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{{asset('assets/template/images/avatar/4.jpg')}}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Rachel Santos</span>
                                <span class="time float-right">15 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="{{asset('assets/template/images/admin.jpg')}}" alt="User Avatar">
                </a>

                <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="#"><i class="fa fa- user"></i>My Profile</a>

                    <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                    <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>

                    <a class="nav-link" href="{{route('logout')}}"><i class="fa fa-power -off"></i>Logout</a>
                </div>
            </div>

        </div>
    </div>
</header>
@endsection

source/resources/views/tenant/backend/baseSidebar.blade.php
@section('sidebar')
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{{route('tenant.index')}}"><i class="menu-icon fa fa-laptop"></i>Dashboard</a>
                    </li>
                    <li class="menu-title">User Settings</li>
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false"> <i class="menu-icon fa fa-shopping-cart"></i>Shops</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-laptop"></i><a href="{{route('tenant.index')}}">Dashboard</a></li>
                        </ul>
                    </li>

                    @php
                        $user = Auth::user();
                        $tenants = $user->tenants()->get();
                    @endphp
                    <li class="menu-title">Shops Management</li>
                    @foreach($tenants as $tenant)
                        <li class="menu-item-has-children dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false"> <i class="menu-icon fa fa-shopping-cart"></i>{{$tenant->name}}</a>
                            <ul class="sub-menu children dropdown-menu">
                                <li><i class="menu-icon fa fa-laptop"></i><a href="{{route('tenant.show', $tenant->id)}}">Dashboard</a></li>
                                <li><i class="menu-icon fa fa-sitemap"></i><a href="{{route('category.index', ['tenant_id' => $tenant->id])}}">Categories</a></li>
                                <li><i class="menu-icon fa fa-anchor"></i><a href="{{route('unit.index', ['tenant_id' => $tenant->id])}}">Units</a></li>
                                <li><i class="menu-icon fa fa-umbrella"></i><a href="{{route('product.index', ['tenant_id' => $tenant->id])}}">Products</a></li>
                                <li><i class="menu-icon fa fa-shopping-cart"></i><a href="{{route('order.index', ['tenant_id' => $tenant->id])}}">Orders</a></li>
                            </ul>
                        </li>
                    @endforeach
                </ul>
            </div>
    </nav>
    </aside>
@endsection